# Welcome to Jekyll!
#

# Site settings
title: Entropy Labs
description: |
  The Starship Technology Research and Development Laboratory
owner: Entropy Labs # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: hello@entropy-labs.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.entropy-labs.de"
social:
  # twitter: https://twitter.com/<username>
  github: https://github.com/entropy-labs
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
